### ISSUE TITLE
When clicking on an image ask whether the user wants to add a comment

### ISSUE THREAD

**Issue by simonv3** [simonv3/annotate#1]
Only add the annotation if there's a comment.

**Comment by neynah** [comment]
+1! Sometimes I miss-click and end up with one or more empty annotations. :sweat_smile:

**Comment by simonv3** [comment]
And they increment automatically, so even if you delete them your annotations could get pretty high!

**Comment by simonv3** [comment]
This is now in the master, let me know what you think. Hopefully by the end of this week I'll be able to wrap up all of those updates and send them on to the Sandstorm publish flow!

**Comment by simonv3** [comment]
Published.
