### ISSUE TITLE
Feature Request: Multiple preview layouts

### ISSUE THREAD

**Issue by neynah** [simonv3/annotate#26]
This is more of a nice-to-have feature but it would be great to be able to toggle between 1 image per row to 2 images per row. 2 images per row would allow users to scan their designs more easily for review (especially when there are a lot of images to look through).

Current:
![annotate1](https://cloud.githubusercontent.com/assets/855341/14396517/e7193792-fd8c-11e5-8e98-69b60392c85c.png)

2-per row:
![annotate2](https://cloud.githubusercontent.com/assets/855341/14396520/e8eaf182-fd8c-11e5-9679-420a68b7568a.png)

**Comment by neynah** [comment]
On second thought, this would be not so trivial if the images are differen't sizes. :(

**Comment by simonv3** [comment]
It might be an idea to just do a "thumbnail" view and a large view? Kind of like Dribbble's display options on a bucket? https://dribbble.com/simonv3/buckets/367913-agenda (top right corner).

**Comment by neynah** [comment]
+1 to thumbnail & large view.

**Comment by simonv3** [comment]
Hey @neynah, I've done a basic version of this:

![screenshot 2016-04-12 15 11 26](https://cloud.githubusercontent.com/assets/485583/14478288/da35e124-00c0-11e6-8178-c9e76ed05188.png)
![Uploading Screenshot 2016-04-12 15.11.17.png…]()

It's on the master branch. 

What this does entail though is that I've removed the ability to add annotations and to see annotations when in the 2-column view. Thoughts on that? If you think you need the annotations in the 2-column view I'm going to have to do some more tinkering (resizing was hurting the percentages).

**Comment by neynah** [comment]
@simonv3 That's really awesome! Ideally it would be nice to be able to add annotations- users might also get confused that they can only add annotations in the 1 column view. Perhaps you can ship adding annotations in the 2-column view in a future release?

What do you mean by "resizing hurting the percentages"?

**Comment by simonv3** [comment]
Resizing the canvas for each image was proving a bit problematic because they're stored by percentage, but it might not be as big of a problem as I imagined. I'll tweak around.
