### ISSUE TITLE
Annotate needs an icon/logo

### ISSUE THREAD

**Issue by neynah** [simonv3/annotate#3]
Hi @simonv3. Do you have any ideas in mind for the icon you'd like for Annotate? Ideas I have so far:
- literal graphic that's a styled "annotate" icon. E.g. a pen & pad / speech bubble
- the word "annotate" styled in freehand/cursive

Btw, I'm roughly aiming to complete this by the end of this week / early next week.

**Comment by simonv3** [comment]
I like the idea of freehand/cursive, but for the rest I honestly have no real opinion on it. No constraints! I'm not sure that makes it easier :P
Thanks so much for doing this!

**Comment by neynah** [comment]
Let me know what you think of these:

![image](https://cloud.githubusercontent.com/assets/855341/12877502/27fb497e-cdc9-11e5-8b4c-d39aee82800b.png)

**Comment by simonv3** [comment]
@neynah these are great! I love the colors. Are you thinking that the background is part of the logo? I would love to see it with the colors reversed if that's not too much trouble - the speech bubble brightly colored, with the lettering white. On a white background (a white background might work better as a logo, whereas the above might work better as an icon on the app store, or maybe I'll let this define the visual style of the actual app as well)? Have you tried that? Could be that it's too much.

I like the big A - though what about an italic variation? Hmm, I looked at some google font As and they don't really look that good italicized.

**Comment by neynah** [comment]
Wow I like them reversed. Yeah, when I designed them I liked the idea of a white bubble over a block of colour, but this would probably only look best as an app icon.

Reversing them and having a white BG allows you to use this in other places as well. I'll see if I can find a reasonable looking italicized "A" and post shortly.
![annotate2](https://cloud.githubusercontent.com/assets/855341/12904156/1bc5fa50-ce82-11e5-97a7-da0b35d42ea9.png)

**Comment by neynah** [comment]
I'd say the regular serif one (above), or the freehand one on the right. Up to you though! :)

![annotate3](https://cloud.githubusercontent.com/assets/855341/12904367/0335b9d8-ce84-11e5-89f8-6b52cd635dd2.png)

**Comment by RichardLitt** [comment]
I like the non-italic purple-blue one. Or the freehand one, for looking more original.

**Comment by simonv3** [comment]
Oooooh. I agree, either the normal A or the "freehand" one. Could you try the freehand one on the purple? I think when it's just a circle like that I prefer the starker contrast of the purple to dark blue. 

Though the freehand one looks like it's already an Apple OS X icon. I'm trying to think of what though :P. (this isn't necessarily a problem)

Thanks so much Néna! These are great.

**Comment by neynah** [comment]
![image](https://cloud.githubusercontent.com/assets/855341/12962644/28c304bc-cffb-11e5-9fa0-3740f14eeb35.png)

I can export your set of icons today if you're happy with either of these. :)

**Comment by simonv3** [comment]
Aah. Seeing the handwritten A on the purple next to the blue I think I actually prefer it on the blue. Thanks for showing them. 

I'm very happy with these :)
