### ISSUE TITLE
Request: Allow grain owner to add annotations

### ISSUE THREAD

**Issue by paulproteus** [simonv3/annotate#5]
Proposed UI:
- User clicks to upload an image or drag'n'drops an image onto the nice big drag'n'drop target
- Drag 'n' drop target goes away, replaced with small text:

> One image added. Click ( + ) to add more images. Annotation is enabled
- Now the grain owner can add annotations and/or share
- The grain owner can click ( + ) and the big drag'n' drop target comes back.
- Whenever the drag 'n' drop target is visible, annotation "doesn't work" - in this sense, doing annotation or doing uploads is modal. Maybe during that time, any existing annotations are grayed-out to indicate that you can't edit annotations at the same time as uploading.

**Comment by simonv3** [comment]
Hey @paulproteus, as part of this (inferring from the title) are you saying that as grain owner you weren't able to add annotations? Is this the same thing as what's described in #8?

The other things are now implemented, but if there's a bug that's preventing the grain owner of adding annotations I should figure that out too.

**Comment by paulproteus** [comment]
Yeah, as grain owner, I wasn't able to add annotations. I didn't try reloading, which Jade (in #8) found worked for her. So probably after a reload it would have worked OK for me.

**Comment by simonv3** [comment]
Cool, I'll investigate. Are you on Chrome?

**Comment by paulproteus** [comment]
Yeah, Chromium on Debian. Details from `about:` aka `chrome://version`:

```
Chromium47.0.2526.80 (Developer Build) Built on Debian stretch/sid, running
on Debian stretch/sid (64-bit)Revision
037a6fde9231f53aa6c5762eb6c5e649ea5068e5OSLinux Blink537.36
(@037a6fde9231f53aa6c5762eb6c5e649ea5068e5)JavaScriptV8
4.7.80.25Flash(Disabled)User
AgentMozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/47.0.2526.80 Safari/537.36Command Line/usr/lib/chromium/chromium
--show-component-extension-options --ignore-gpu-blacklist
--ppapi-flash-path=/usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so
--ppapi-flash-version --flag-switches-begin --disable-quic
--flag-switches-endExecutable Path/usr/lib/chromium/chromiumProfile
Path/home/paulproteus/.config/chromium/DefaultVariations16e0dd70-3f4a17df
f1eb96ab-3f4a17df
775ebbd7-3f4a17df
97dfc274-3f4a17df
4ea303a6-3f4a17df
fa99bb73-3f4a17df
5c3cc7b1-3f4a17df
```

**Comment by paulproteus** [comment]
Thanks so much! It's a joy to watch this app improve so quickly, and the
code is fun to read, too. I don't know much about Angular so it's nice to
be part of a project that uses it and see how you are using it.

**Comment by simonv3** [comment]
Disclaimer: don't assume the code written above is a good indicator of How To Write Angular. :P

**Comment by paulproteus** [comment]
noted!
